name: Sync upstream

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: update upstream
        run: |
          git remote add upstream https://github.com/qmk/qmk_firmware.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          git push origin master
